name: Sync with Upstream

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main # Checkout the main branch
          fetch-depth: 0 # Fetch all history for all branches and tags

      # Add the upstream remote and fetch changes
      - name: Add upstream remote and fetch changes
        run: |
          git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
          git fetch upstream

      # Merge changes from upstream/master into main
      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge upstream/master --no-edit

      # Push the updated main branch to your repository
      - name: Push changes
        run: git push origin main
